#!/bin/zsh

autoload -U add-zsh-hook
export ENVDIR=$(dirname $0:A)

source $ENVDIR/functions
source $ENVDIR/hooks

if [[ -f $PWD/.envrc ]] then
	echo "Entering an envdirred folder"
	pushenv
	source $PWD/.envrc
fi